#!/bin/bash
#1 descarga

sudo git clone https://github.com/OCA/account-financial-reporting.git -b 8.0 /opt/odoo/account-financial-reporting
sudo git clone https://github.com/OCA/account-financial-tools.git -b 8.0 /opt/odoo/account-financial-tools
sudo git clone https://github.com/OCA/knowledge.git -b 8.0 /opt/odoo/knowledge
sudo git clone https://github.com/OCA/l10n-spain.git -b 8.0 /opt/odoo/l10n-spain
sudo git clone https://github.com/OCA/bank-payment.git -b 8.0 /opt/odoo/bank-payment
sudo git clone https://github.com/OCA/reporting-engine.git -b 8.0 /opt/odoo/reporting-engine


